version: 2

jobs:
  build:
    working_directory: ~/translator
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          - DB_USERNAME= translator
          - DB_PASSWORD= translator
          - DB_HOST= localhost
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=translator
          - MYSQL_DATABASE=translator_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ .Branch }}
            - gem-cache
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: gem-cache-{{ .Branch }}
          paths:
            - vendor/bundle
      - save_cache:
          key: gem-cache
          paths:
            - vendor/bundle
      - run: bundle exec rake db:migrate
      - run: bundle exec rake test